INSERT INTO "level" VALUES(1,'Level 1','An introduction to basic Secondary School Mathematics and a starting foundation to improve your Mathematical understanding. This Level includes 4 main topics: Shape, Number, Algebra, and Data. The level encompasses within the main topics, 2D and 3D shapes, Counting, Fractions, Linear Equations and more. ');
INSERT INTO "level" VALUES(2,'Level 2','A progression on Level 1, consisting of the recurring 4 topics: Shape, Number, Algebra and Data. This would be equivalent to lower Secondary School level. The level encompasses within the main topics, Symmetry, Percentages, Ratio and Proportion, Inequalities, Processing Data and many more. ');
INSERT INTO "level" VALUES(3,'Level 3','An introduction to a harder progression of the previous topics. Building a knowledgeable foundation to improve your Mathematical understanding. This Level includes 4 main topics: Shape, Number, Algebra, and Data.  The level encompasses within the main topics, Angles, Converting Units, Fractions, Co-Ordinates and more. ');
INSERT INTO "level" VALUES(4,'Level 4','A progression on Level 3, consisting of the recurring 4 topics: Shape, Number, Algebra and Data. Building the final foundations of advancing to high level in secondary school. The level encompasses within the main topics, Pythagoras, Volume and Surface Area, Inequalities, Powers and Roots, Probability and more. ');
INSERT INTO "level" VALUES(5,'Level 5','This level will be covering the core and pure modules within mathematics. The core modules cover the basic foundation to understanding Mathematics at Higher Education. The level encompasses the main topics such as Algebra, Differentiation, Integration, Logarithms, Exponentials and Trigonometry, Vectors and many more. ');
INSERT INTO "level" VALUES(6,'Level 6','This level will be looking at Decision Mathematics. Decision Mathematics is an applied module which can be applied to problems in everyday life. Topics included in this level are: Algorithms, Graphs, Networks, Linear Programming, Game Theory, Flow Charts and many more. ');
INSERT INTO "level" VALUES(7,'Level 7','This level will be looking at Statistical Mathematics. Statistics is an applied module which can be used for problems in everyday life. Topics included in this level are: Probability, Normal Distribution, Sampling and many more.');
INSERT INTO "level" VALUES(8,'Level 8','This level will be looking at Mechanical Mathematics. Mechanics is an applied module, used frequently which Physics. Topics included in this level are: Vectors, Momentum, Moments, Forces and many more.');
INSERT INTO "level" VALUES(9,'Level 9','Level 9 Info');
INSERT INTO "level" VALUES(10,'Level 10','Level 10 Info');
INSERT INTO "levelsection" VALUES(1,1,'Shapes','images/grey.png');
INSERT INTO "levelsection" VALUES(1,2,'Number','images/grey.png');
INSERT INTO "levelsection" VALUES(1,3,'Algebra','images/grey.png');
INSERT INTO "levelsection" VALUES(1,4,'Data','images/grey.png');
INSERT INTO "levelsection" VALUES(2,5,'Shape','level2/images/level2shape.png');
INSERT INTO "levelsection" VALUES(2,6,'Number','images/grey.png');
INSERT INTO "levelsection" VALUES(2,7,'Algebra','images/grey.png');
INSERT INTO "levelsection" VALUES(2,8,'Data','images/grey.png');
INSERT INTO "levelsection" VALUES(3,9,'Shape','images/grey.png');
INSERT INTO "levelsection" VALUES(3,10,'Number','images/grey.png');
INSERT INTO "levelsection" VALUES(3,11,'Algebra','images/grey.png');
INSERT INTO "levelsection" VALUES(4,12,'Shape','images/grey.png');
INSERT INTO "levelsection" VALUES(4,13,'Number','images/grey.png');
INSERT INTO "levelsection" VALUES(5,14,'Algebra ','images/grey.png');
INSERT INTO "levelsection" VALUES(3,15,'Data','images/grey.png');
INSERT INTO "levelsection" VALUES(4,16,'Algebra','images/grey.png');
INSERT INTO "levelsection" VALUES(4,17,'Data','images/grey.png');
INSERT INTO "levelsection" VALUES(5,18,'Co-ordinate Geometry ','images/grey.png');
INSERT INTO "levelsection" VALUES(5,20,'Graphs','images/grey.png');
INSERT INTO "levelsection" VALUES(5,23,'Sequences, series ','images/grey.png');
INSERT INTO "levelsection" VALUES(5,25,'Calculus','images/grey.png');
INSERT INTO "levelsection" VALUES(5,26,'Logs','images/grey.png');
INSERT INTO "levelsection" VALUES(5,27,'Trig ','images/grey.png');
INSERT INTO "levelsection" VALUES(5,29,'Exponentials','images/grey.png');
INSERT INTO "levelsection" VALUES(5,30,'Vectors','images/grey.png');
INSERT INTO "levelsection" VALUES(6,33,'Algorithms ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,34,'Graphs and networks ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,35,'Algorithms on graphs ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,36,'Route inspection ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,37,'Linear Programming ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,38,'Critical path analysis ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,39,'Matchings ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,40,'Transportation ','images/grey.png');
INSERT INTO "levelsection" VALUES(6,41,'Allocation Problems','images/grey.png');
INSERT INTO "levelsection" VALUES(6,42,'Further Linear Programming','images/grey.png');
INSERT INTO "levelsection" VALUES(6,43,'Game Theory','images/grey.png');
INSERT INTO "levelsection" VALUES(6,44,'Flows in Networks','images/grey.png');
INSERT INTO "levelsection" VALUES(6,45,'Dynamic Programming','images/grey.png');
INSERT INTO "levelsection" VALUES(7,46,'Representation of data ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,47,'Averages ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,48,'Standard deviation ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,49,'Probability ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,50,'Correlation','images/grey.png');
INSERT INTO "levelsection" VALUES(7,51,'Discrete Random Variables ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,52,'Normal distribution ','images/grey.png');
INSERT INTO "levelsection" VALUES(7,53,'The binomial + poisson distributions','images/grey.png');
INSERT INTO "levelsection" VALUES(7,54,'Hypothesis tests','images/grey.png');
INSERT INTO "levelsection" VALUES(8,55,'Vectors ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,56,'Kinematics ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,57,'Newtons Law ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,58,'Forces at angles ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,59,'Friction ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,60,'Momentum ','images/grey.png');
INSERT INTO "levelsection" VALUES(8,61,'Moments','images/grey.png');
INSERT INTO "levelsection" VALUES(8,62,'Projectiles ','images/grey.png');
INSERT INTO "quizquestions" VALUES(2,7,'What is 40% of 25?','5','25','10','20','C');
INSERT INTO "quizquestions" VALUES(2,8,'Solve 4x – 9 > 35?','14','11','12','16','B');
INSERT INTO "quizquestions" VALUES(2,9,'243 x 83 = ?','20169','20149','20153','20147','A');
INSERT INTO "quizquestions" VALUES(2,10,'Find the nth term of 6, 19, 45, 97,201','7n','2n+4','2n+7','7n+2','C');
INSERT INTO "quizquestions" VALUES(2,11,'If the diameter of a circle is 10cm, what is its circumference?','31.14','31.42','30.34','31.54','B');
INSERT INTO "quizquestions" VALUES(2,12,'In the upper quartile range is 19.7 and the lower quartile range is 4.3, what is the Inter-quartile range?','15.4','15.6','14.4','15.3','A');
INSERT INTO "quizquestions" VALUES(2,13,'In a triangle, if one angle is 35 degrees and another angle is 62 degrees, what is the third angle? Giving your answer in degrees?','74','83','73','84','B');
INSERT INTO "quizquestions" VALUES(2,14,'Where does 3x + 4 cross the x- axis?','8','3','5','4','D');
INSERT INTO "quizquestions" VALUES(2,15,'If you roll a fair 6 sided dice 1500 times, how often would you expect to get a 6?','350','600','250','500','C');
INSERT INTO "quizquestions" VALUES(2,16,'What is the volume of the prism with a width of 4cm, height 5cm and length 6cm?','60cm³','50cm³','120cm³','80cm³','A');
INSERT INTO "quizs" VALUES(2,'Level 2');
INSERT INTO "topics" VALUES(5,1,'Pythagoras','level2/Pythagoras.rst');
INSERT INTO "topics" VALUES(5,2,'Symmetry','level2/Symmetry.rst');
INSERT INTO "topics" VALUES(5,3,'Transformations','level2/Transformations.rst');
INSERT INTO "topics" VALUES(6,6,'Multiply/Divide ','level2/MultiDiv.rst');
INSERT INTO "topics" VALUES(6,7,'Percentages ','level2/Percentages.rst');
INSERT INTO "topics" VALUES(6,8,'Powers + Roots ','level2/Powers.rst');
INSERT INTO "topics" VALUES(6,9,'Ratio and proportion ','level2/Ratios.rst');
INSERT INTO "topics" VALUES(6,10,'Standard Form ','');
INSERT INTO "topics" VALUES(7,11,'Graphs ','');
INSERT INTO "topics" VALUES(7,12,'Inequalities ','level2/Inequalities.rst');
INSERT INTO "topics" VALUES(7,13,'Sequences ','level2/Sequences.rst');
INSERT INTO "topics" VALUES(8,14,'Processing Data ','');
INSERT INTO "topics" VALUES(8,15,'Probability ','');
INSERT INTO "topics" VALUES(1,16,'2D/3D Shapes ','');
INSERT INTO "topics" VALUES(1,17,'Angles ','');
INSERT INTO "topics" VALUES(1,18,'Area + Perimeter ','');
INSERT INTO "topics" VALUES(1,19,'Construction ','');
INSERT INTO "topics" VALUES(1,20,'Converting Units ','');
INSERT INTO "topics" VALUES(1,21,'Measures ','');
INSERT INTO "topics" VALUES(2,22,'Add/Subtract Mental ','');
INSERT INTO "topics" VALUES(2,23,'Counting and place value ','');
INSERT INTO "topics" VALUES(2,24,'Decimals ','');
INSERT INTO "topics" VALUES(2,25,'Estimating + Accuracy ','');
INSERT INTO "topics" VALUES(2,26,'Fractions ','');
INSERT INTO "topics" VALUES(2,27,'Money Problems ','');
INSERT INTO "topics" VALUES(3,28,'Algebraic Manipulation ','');
INSERT INTO "topics" VALUES(3,29,'Co-ordinates ','');
INSERT INTO "topics" VALUES(3,30,'Linear Equations ','');
INSERT INTO "topics" VALUES(3,31,'Expressions and Formulae ','');
INSERT INTO "topics" VALUES(4,32,'Presenting Data ','');
INSERT INTO "topics" VALUES(9,33,'2D/3D Shapes ','');
INSERT INTO "topics" VALUES(9,34,'Angles ','');
INSERT INTO "topics" VALUES(9,35,'Area + Perimeter ','');
INSERT INTO "topics" VALUES(9,36,'Construction ','');
INSERT INTO "topics" VALUES(9,37,'Converting Units ','');
INSERT INTO "topics" VALUES(9,38,'Measures ','');
INSERT INTO "topics" VALUES(10,39,'Add/Subtract Mental + Written Form ','');
INSERT INTO "topics" VALUES(10,40,'Counting and place value ','');
INSERT INTO "topics" VALUES(10,41,'Decimals ','');
INSERT INTO "topics" VALUES(10,42,'Estimating + Accuracy ','');
INSERT INTO "topics" VALUES(10,43,'Fractions ','');
INSERT INTO "topics" VALUES(10,44,'Money Problems ','');
INSERT INTO "topics" VALUES(11,45,'Algebraic Manipulation ','');
INSERT INTO "topics" VALUES(11,46,'Co-ordinates ','');
INSERT INTO "topics" VALUES(11,47,'Linear Equations ','');
INSERT INTO "topics" VALUES(11,48,'Expressions and Formulae ','');
INSERT INTO "topics" VALUES(15,49,'Presenting Data ','');
INSERT INTO "topics" VALUES(12,50,'Pythagoras (3D)','');
INSERT INTO "topics" VALUES(12,51,'Scale and similarity ','');
INSERT INTO "topics" VALUES(12,52,'Trigonometry ','');
INSERT INTO "topics" VALUES(12,53,'Transformations ','');
INSERT INTO "topics" VALUES(12,54,'Volume + Surface area ','');
INSERT INTO "topics" VALUES(13,55,'Multiply/Divide Mental +Written ','');
INSERT INTO "topics" VALUES(13,56,'Percentages ','');
INSERT INTO "topics" VALUES(13,57,'Powers + Roots ','');
INSERT INTO "topics" VALUES(13,58,'Ratio and proportion ','');
INSERT INTO "topics" VALUES(13,59,'Standard Form ','');
INSERT INTO "topics" VALUES(16,60,'Graphs ','');
INSERT INTO "topics" VALUES(16,61,'Inequalities ','');
INSERT INTO "topics" VALUES(16,62,'Sequences ','');
INSERT INTO "topics" VALUES(17,63,'Processing Data ','');
INSERT INTO "topics" VALUES(17,64,'Probability ','');
INSERT INTO "topics" VALUES(5,65,'Volume and Surface Area','level2/VolumeandSurfaceArea.rst');

